# JVM 参数：Compose 编译较吃内存，给足堆。
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# 并行 + 构建缓存（本地开发提速）
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# AndroidX（非 support 库）
android.useAndroidX=true

# Kotlin 官方代码风格
kotlin.code.style=official

# 只打包实际用到的资源
android.nonTransitiveRClass=true
